### ISSUE TITLE
Unknown user and password is used for connecting to p-mysql database service

### ISSUE THREAD

**Issue by Spiti** [SteeltoeOSS/Samples#10]
when using command 'pushShoppingCartService.cmd ubuntu.14.04-x64 netcoreapp1.1' the application crashes because it is not able to connect to database. How can I change the username and password? Please see the printscreen attached.
![crede](https://cloud.githubusercontent.com/assets/8936434/24305947/671aa2de-10c7-11e7-93c9-1fa83d15bf17.PNG)

**Comment by Spiti** [comment]
The isssue was that the user has no permissions to alter the database.

**Comment by dtillman** [comment]
@Spiti : Were you able to get this working or are you still having problems?

**Comment by Spiti** [comment]
The issues was that the user did not have rights to alter the database. I connected to the db, using local Mysql Workbench and I added rights to that user. How can I do that on binding?

**Comment by dtillman** [comment]
@Spiti: 
I would think the username/password provided by the binding would have all the rights you would need to create/alter/etc.

This could be an issue with how the MySQL installation works on PCF DEV.
Can you tell me what version of PCF Dev you are working with?

Dave
