### ISSUE TITLE
Working example of console application performing Service Discovery

### ISSUE THREAD

**Issue by dlane771** [SteeltoeOSS/Samples#108]
Hi. I have been trying to create a working example of a .NET console application that will perform service discovery to a Service Registry (Eureka) deployed in PCF. We are architecting a solution that has "processors" that need to discover services. These processors are console applications.

I was leveraging an existing example found at 
https://github.com/SteeltoeOSS/Samples/tree/dev/Discovery/src/Console

However I can't get it working in PCF.

The binding of the configuration to the EurkaClientConfig does not seen to fully work.
           var clientConfig = new EurekaClientConfig();
            ConfigurationBinder.Bind(configuration.GetSection("eureka:client"), clientConfig);

The appsettings.json in the sample app has a setting called eureka:client:serviceUrl. The ErrekaClientConfig class has a setting called EurekaServerServiceUrls. So the service URL does not get populated from appsettings.json. From the sample, it is a coincidence that they are the same URL ("http://localhost:8761/eureka/") after the configuration binding. So this sample may work with a locally running Eureka Discovery Sevrice, but not on PCF using the configuration in appsettings.json. 

Even when I manually set the EurekaServerServiceUrls with the URL of the deployed Service Registry, it does not work despite having a registered application. I wonder if I need to use Service Key Credentials such as eureka:client:clientId, and eureka:client:clientSecret which I have set up in PCF for the Service Registry. However I have no idea to get these credentials into the ErrekaClientConfig in the sample console application.

**Comment by TimHess** [comment]
Hello, sorry about the delayed response!

That sample was not built for deployment to PCF (nothing is reading the CloudFoundry Config). If you're using a Spring Cloud Services Eureka server, which it sounds like you are, you definitely need the client id and secret.

I'll push an update of the sample that will read in a service binding shortly...

**Comment by mandar14** [comment]
Hello @TimHess and others, 
 I'm trying to push fortune-teller app (https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/AspDotNetCore)
On my cf environment I have eureka service created via cups for which actual server running on other VM.

I'm facing similar issue, in CF logs, I can see it is trying to connect to localhost:8761 even after binding with cups.

Could this be same rootcause, does this app also missing vcap_services details reader.

PS: Manually updating appsettings.json with eureka-urls works, I can see app on eureka-dashboard.

**Comment by TimHess** [comment]
For readers from the future, the binding needs to be identifiable as a service of the desired type ~ in this case, adding a tag of `eureka` solved it
