### ISSUE TITLE
How long does it take to fire mvn spring-boot:run to be up and running ?

### ISSUE THREAD

**Issue by RushikeshWalnut** [SteeltoeOSS/Samples#111]

**Comment by TimHess** [comment]
You'll have to be a little more specific with regard to which application you're referring to... It will depend on the speed of your internet connection and hardware, especially on the first run. On my machine, config server and Eureka server are almost always up and running in under 30 seconds

**Comment by TimHess** [comment]
There doesn't appear to be anything for Steeltoe to do to help you out here, please let us know if you have additional questions
