### ISSUE TITLE
CloudFoundrySingleSignon sample credentials.json?

### ISSUE THREAD

**Issue by reneherrero** [SteeltoeOSS/Samples#12]
Hi,

Forgive me for what may sound like a newbie question, venturing off into unknown territory...

I need to get SSO working at my org and am going through the CloudFoundrySingleSignon sample.  This looks odd: (credentials.json file)
{
  "client_id": "myTestApp",
  "client_secret": "myTestApp",
  "uri": "uaa://login.<YOUR-CLOUDFOUNDRY-SYSTEM-DOMAIN>"
}
Storing credentials is source control is a big no no... any alternate way to do this?

Thanks,

Rene

**Comment by dtillman** [comment]
reneherrero: Have a look at this PCF service:   https://network.pivotal.io/products/p-identity. 
Documentation here: http://docs.pivotal.io/p-identity/1-3/index.html
