### ISSUE TITLE
.Net framework 4.6.2 could not complete build

### ISSUE THREAD

**Issue by AsawinK-at-362531566303** [SteeltoeOSS/Samples#123]
.Net framework 4.6.2 could not complete build, do you have option for me?

**Comment by TimHess** [comment]
I'm unclear on what isn't building, there are a number of samples in this repository... Could you please clarify which sample you're working with and include some more information like what OS (version) you're running, what Visual Studio version you're using and the build failure message(s)?

**Comment by AsawinK-at-362531566303** [comment]
I am working on asp.Net mvc framework 4.6.2 unfortunately I cannot install package from nugget it said not suitable with my framework

Also I was working on sample code framework 4.6.1 unfortunately which is successful build but found error as well


[cid:image002.png@01D59303.3A2FE520]



Asawin  Kongthaworn
Manager - Bank Partner Solution Engineer 1

FWD Life Insurance Public Company Limited
14th, 16th, 27th, 28th, 29th Floor, 130-132 Sindhorn Building Tower 3, Wireless Road, Lumpini, Pathumwan, Bangkok 10330

T       (66) 2207 5603
E       AsawinK@fwd.co.th<mailto:AsawinK@fwd.co.th>
W       fwd.co.th<https://www.fwd.co.th>

**Comment by TimHess** [comment]
Which Steeltoe package? What version of Visual Studio?
You may need to update Visual Studio and/or you NuGet client

**Comment by TimHess** [comment]
As it's been 5 weeks with no response, I'm going to assume this was an issue with your development environment (Visual Studio/NuGet client) rather than an issue with Steeltoe packages, and that you require no further assistance. Please re-open the issue if you feel there is an issue for us to address.

Thanks
