### ISSUE TITLE
Create samples for metrics using OpenTelelmetry for Zipkins and PCF Metrics

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/Samples#126]
Please create a sample that shows how to use OpenCensus to export metrics to Zipkin & PCF metrics

**Comment by hananiel** [comment]
I updated the [Cloud Foundry Sample](https://github.com/SteeltoeOSS/Samples/commit/eafe4855b866daf44fe613799542284c2249dfef) to show metrics usage using the new Prometheus exporter and the new metrics registrar. The existing tracing sample in the [master](https://github.com/SteeltoeOSS/Samples/tree/master/Management/src/Tracing) branch shows usage with Zipkin.

**Comment by hananiel** [comment]
Closing for now but feel free to reopen if needed.
