### ISSUE TITLE
Code: 67, Error: Bad Net Name

### ISSUE THREAD

**Issue by pnguyen535** [SteeltoeOSS/Samples#127]
Hi,

I am trying to use SMB, but it throws exception Code: 67, Error: Bad Net Name

Code: 67, Error: Bad Net Name

Have anyone run into this issue?

Thanks

**Comment by TimHess** [comment]
This issue is likely to occur when you provide a local path instead of a UNC path. The expectation (of both Steeltoe and the underlying libraries) is that you will provide the path in the form `\\server\path\to\share`

How are you describing the location of the SMB share?

**Comment by pnguyen535** [comment]
Hi Tim,

I tried the following, but none of them work. 
\\servername\path\
\\server address\path\

Thank you

**Comment by TimHess** [comment]
This error message is coming from Windows, it's only passing through Steeltoe. Have you validated that you can access the share from the location the app is running? Could there be networking issues if you're 100% sure the path is correct?

https://stackoverflow.com/questions/9705535/how-can-i-resolve-a-error-bad-net-name-error-in-a-call-to-wnetaddconnection2

**Comment by TimHess** [comment]
This issue should have been resolved with 2.4.1, please re-open if it persists
