### ISSUE TITLE
Consider alternatives to a shared "version.props"

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Samples#136]
Ideally each Sample is a self-contained application with no source or config dependencies outside of the Sample's root directory.  Doing so would make it easier to run a Sample in a local Docker environment.

Instead of shared configurations, perhaps a generated config per sample.

Perhaps of use, here's an example of a project whose dependency configs are store outside of the project file.
https://github.com/dotnet/aspnetcore/blob/master/src/DataProtection/DataProtection/src/Microsoft.AspNetCore.DataProtection.csproj

**Comment by TimHess** [comment]
I think we can consider this issue resolved thanks to @korser1
