### ISSUE TITLE
Is there any stepbystep or video tutorial on  (Service Discovery ) what exact changes we need to do in order to register a service in to spring cloud eureka and also to write a client to consume this service ??

### ISSUE THREAD

**Issue by gsainagendraprasad** [SteeltoeOSS/Samples#14]
This samples are great, but is there any tutorial available to start from scratch. There is code related to service discovery and client that needs to be written in many files like program.cs, startup.cs, appsettings.json, package.json and manifest.yml.
 
I am able to write services but i am not sure what are all the changes i need to make in my code in order to register it into Spring Cloud Eureka Server.

**Comment by dtillman** [comment]
@gsainagendraprasad : 
You can take a look at the Steeltoe documentation:  http://steeltoe.io/docs/

You can take a look at the Steeltoe Workshop material: https://github.com/SteeltoeOSS/Workshop . 
I would recommend walking through the Workshop labs by following the lab write-ups.

**Comment by gsainagendraprasad** [comment]
@dtillman Thank you Dave.
