### ISSUE TITLE
Remove 4.x samples from master and clean up directory structure

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Samples#141]
1. Clean up for `Master` branch (also currently known as 3.0 branch) to remove all 4.x samples, since Steeltoe 3.0 will focus on .NET Core only.  
2. Simplify the directory structure by removing `AspDotNetCore` subfolder since `AspDotNet4` folder will be completely removed and there will not longer be a need to distinguish between them.

**Comment by ccheetham** [comment]
Structural changes completed
