### ISSUE TITLE
Review current samples and make necessary changes to use new Steeltoe 3.x changes

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Samples#142]
## Describe the solution you'd like
The Samples for Steeltoe 3.0 (master) need to reflect the updates we have added.  
This ticket requests a complete review of the Samples in the repo to update them for the latest implementation.

**Comment by ccheetham** [comment]
probably resolved by 60931043c20fdc2c8f760fe9dfaca252fb25c4c4
