### ISSUE TITLE
Create sample that uses the AddAllActuators without CF

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Samples#155]

**Comment by hananiel** [comment]
The [SpringBootAdmin] (https://github.com/SteeltoeOSS/Samples/tree/master/Management/src/SpringBootAdmin) Sample demonstrates this feature in its [Program.cs](
https://github.com/SteeltoeOSS/Samples/blob/e5e86c30be3cfd010997576f8692bdf383ae8bf2/Management/src/SpringBootAdmin/Program.cs#L26)
