### ISSUE TITLE
Add support for .Net 5

### ISSUE THREAD

**Issue by ccheetham** [SteeltoeOSS/Samples#157]
https://devblogs.microsoft.com/dotnet/introducing-net-5/
https://dotnet.microsoft.com/download/dotnet/5.0

**Comment by TimHess** [comment]
It looks like we're going to need to update targeting on all Steeltoe packages that currently target `netcoreapp3.1` to avoid messages like this... 

```
Package Steeltoe.Common.Hosting 3.0.1 is not compatible with net50 (.NETFramework,Version=v5.0). Package Steeltoe.Common.Hosting 3.0.1 supports: netcoreapp3.1 (.NETCoreApp,Version=v3.1)
```
