### ISSUE TITLE
dotnet restore returns 404 due to broken link

### ISSUE THREAD

**Issue by belinda-liu** [SteeltoeOSS/Samples#158]
Hi there,

We are using the Management/AspDotNetCore/CloudFoundry sample and are running into a 404 when trying to perform a `dotnet restore --configfile nuget.config`.

```
$ dotnet restore --configfile nuget.config

Determining projects to restore...
/usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error : Unable to load the service index for source https://www.myget.org/F/steeltoemaster/api/v3/index.json. [/tmp/build/89da190e/steeltoe-samples/Management/src/AspDotNetCore/CloudFoundry/CloudFoundry.csproj]
/usr/share/dotnet/sdk/3.1.301/NuGet.targets(128,5): error :   Response status code does not indicate success: 404 (Feed does not exist.). [/tmp/build/89da190e/steeltoe-samples/Management/src/AspDotNetCore/CloudFoundry/CloudFoundry.csproj]
```
It seems like the link no longer has any valid content. Is there an immediate workaround we can use?

Thanks,
@belinda-liu && @weymanf

**Comment by TimHess** [comment]
Sorry about that! We removed that feed last week as we haven't published to it in over a year. It should work fine if you remove that feed from the file and try again.

**Comment by belinda-liu** [comment]
Thanks for the quick response! We just confirmed that removing the SteelToeMaster feed worked for us.

Will this change be committed? We're relying on automatically pulling this repo in our CI setup, so manually changing the config each time would be a headache.

**Comment by TimHess** [comment]
Yes.  A quick search found 33 instances, so it might take a few minutes... We'd be interested in hearing how this repo is part is your CI setup - cc @ccheetham

**Comment by weymanf** [comment]
We wrote an app on cloudfoundry (appsmanager) that reads actuator info and surfaces that to users. We deploy the steeltoe sample app for our integration tests to ensure that contract doesn't break.

**Comment by TimHess** [comment]
Oh, sure I know about that app and that process! Which branch are you testing?

**Comment by belinda-liu** [comment]
We're pulling in the default, so 2.x.

Our pipeline just went green, thanks a bunch! Feel free to close this issue.

**Comment by TimHess** [comment]
3.0 will be a significant release for us, but 2.x will be around for a while as well, if you could add a pipeline for 3.0 (the sample should operate virtually identically, just using newer runtime & packages) it would probably be good for all of us. 

Thanks for reporting the issue!
