### ISSUE TITLE
Can't connect to Eureka for service registry

### ISSUE THREAD

**Issue by pieterderycke** [SteeltoeOSS/Samples#16]
I have a running instance of Eureka 1.7.0 running on Tomcat 8.5, when I surf to Eureka the management screen is working fine. I downloaded the Eureka directly from Netflix OSS.

When I try to connect with a simple ASP.NET Core Web API project it does not work. I get the following error in the output screen: "Steeltoe.Discovery.Eureka.DiscoveryClient:Error: HeartBeat failed"

Is there a way to get more info about why the heartbeat failed? or is steeltoe not compatible with Eureka 1.7.0?

This is my appsettings.json:

`{
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Information",
      "Pivotal": "Debug",
      "Steeltoe": "Information"
    }
  },
  "spring": {
    "application": {
      "name": "EurekaDiscoveryService"
    }
  },
  "eureka": {
    "client": {
      "serviceUrl": "http://localhost:8080/",
      "shouldFetchRegistry": false
    },
    "instance": {
      "port": 50612
    }
  }
}`

**Comment by dtillman** [comment]
Change from "Information" to "Debug" for the Steeltoe category
