### ISSUE TITLE
Logging not working (example project)

### ISSUE THREAD

**Issue by dothem1337** [SteeltoeOSS/Samples#173]
After trying to log with the Steeltoe Serilog extenation in my own application without any success, I cloned your example project to try, if the mistake is on my side or not.

I'm also not able to log to console in the example project. Just checked out, run. Because in the appsettings it's defined like in the Steeltoe documentation to log to console, but i dont see the logs which are in the HomeController.cs.

Can anyone please check this, or am I missing something?

**Comment by dothem1337** [comment]
Sorry for the circumstances, the logs are working in the example project. I checked twice, but the logs are printed differently in this project, don't know why, but i found them now. I will compare this project to with my project. Issue can be closed/deleted so far, will make another comment, if there are still questions / problems.

**Comment by hananiel** [comment]
@dothem1337 which sample and branch are you referring to? Couple of quick things to check is - if using IIS the logs show up in output window but you have to select the webserver logs.

**Comment by dothem1337** [comment]
Everything good. The problem was that I was using `var host = new WebHostBuilder()` instead of `var host = WebHost.CreateDefaultBuilder()` and that causes, that no logs were printed. As far I know, normal Serilog logging without Steeltoe worked this way.

**Comment by hananiel** [comment]
If using Kestrel,  Adding
 ```
.UseKestrel()
.ConfigureAppConfiguration(config => config.AddJsonFile("appsettings.json", true, true))
``` 
 also works with our sample. Also see : https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.webhost.createdefaultbuilder?view=aspnetcore-3.1.
