### ISSUE TITLE
Command, .\runMusicStoreUI.cmd ended up throwing an error

### ISSUE THREAD

**Issue by Isuama** [SteeltoeOSS/Samples#18]
Executing command, .\runMusicStoreUI.cmd throws an error and stopped the service.
![capture4](https://user-images.githubusercontent.com/19770357/29121373-eaab0fe6-7d2b-11e7-8271-66b93666045f.PNG)

**Comment by rschiefer** [comment]
I found this error as well.  I believe I is related to https://github.com/aspnet/Identity/issues/1012

**Comment by rschiefer** [comment]
You can comment line 27 of the MusicStoreUI.Models.SampleData class to workaround this error and see the site working with basic functionality.  

![image](https://user-images.githubusercontent.com/1071761/29210549-bb1b660c-7e59-11e7-9bdb-2d70c72e6266.png)

You won't have an admin user or be able to see the admin side of the site.

**Comment by dtillman** [comment]
Thanks @Isuama, 
I'll take a look at this shortly. 
Dave

**Comment by dtillman** [comment]
@Isuama
I have updated the music store app with various changes and tested it by running it locally and also pushing it to Cloud Foundry.
 
Right now all of the changes that I made are on the dev branch ... if you want to test it out again.

Please feel free to open up another issue if you run into problems.

Dave
