### ISSUE TITLE
CloudFoundry sample for Management endpoint doesn't push

### ISSUE THREAD

**Issue by macsux** [SteeltoeOSS/Samples#184]
This sample doesn't push out of the box
https://github.com/SteeltoeOSS/Samples/tree/main/Management/src/CloudFoundry

Few issues:
1. manifest should not have a startup command - this is set by buildpack
2. I think the presence of multiple TargetFrameworks confuses buildpack. Need to publish it with `-r` and push binaries.

**Comment by TimHess** [comment]
@macsux I'm not sure why `windows-manifest.yml` is specifying `hwc_buildpack`, it's [supposed to be `binary_buildpack`](https://docs.pivotal.io/application-service/2-11/buildpacks/binary/index.html#dotnet-console), which prevents us from enabling `cf push` without publish in some scenarios, which then requires us to either describe all of that more in depth, or just leave it with a standard explanation/requirement to publish first.

We also use this sample for integration testing, which requires us to be able to `cf push` to Windows and Linux across .NET Core 3.1 and .NET 5.0, so I'm not really inclined to address your second item, but we can at least remove the startup command from the Linux manifest
