### ISSUE TITLE
Need to update tracing sample with new Otel/Dotnet Api for traces

### ISSUE THREAD

**Issue by hananiel** [SteeltoeOSS/Samples#185]
Currently the tracing sample has this [line ](https://github.com/SteeltoeOSS/Samples/blob/ae466a07646298b09a888933d4bd2f02d368657c/Management/src/Tracing/Fortune-Teller-Service/Models/FortuneRepository.cs#L45) commented out. It needs to be replaced with something like the following ... 
` using (var activity = MyActivitySource.StartActivity("SayHello"))`

**Comment by jkonicki** [comment]
Need to investigate if this change works with current OTel code.
