### ISSUE TITLE
Cannot execute "dotnet publish" command on MySqlEfCore project

### ISSUE THREAD

**Issue by Isuama** [SteeltoeOSS/Samples#21]
I get an error when I execute this command. I have tested on .netcoreapp 2.0 as well as 1.1. Is this a kind of VS error? I cannot even build the project using VS 2017. I have pulled out the dev branch for this development.
![image](https://user-images.githubusercontent.com/19770357/29700711-a52ab128-8984-11e7-9672-37727c59474f.png)

Without building the project I have tried out to push to the cloud foundry by using "cf push" and still get the common error as BuildpackCompileFailed.

![image](https://user-images.githubusercontent.com/19770357/29701069-1bdc4d98-8987-11e7-9b5d-0578e8e885ec.png)

**Comment by dtillman** [comment]
@Isuama 
This is a dotnet tooling "issue" ..  you can no longer publish to a directory that is a directly in the projects root... (i.e. -o publish).  Once that directory exists (i.e. publish) .. the next time you build it will screw up the build...  So 'rmdir /s /q publish'   and then publish again...

Your best to just 'dotnet publish -f xxx -r yyy' ... and use the default publish output directory the tooling selects (i.e. bin\Debug\netcoreapp2.0\ubuntu.14.04-x64\publish) ...  then cf push -f manifest.yml  -p bin\..... "

Hope that helps

Dave

**Comment by Isuama** [comment]
Yes that's correct. But in my case I have gone through Steeltoe doc to run those commands and pulled new version from dev branch which made conflict on netcoreapp1.1 and 2.0. I just removed all files and pulled from the master branch and it is working perfectly. Thanks mate
