### ISSUE TITLE
What is the proper way of Consuming a Service Registry

### ISSUE THREAD

**Issue by Isuama** [SteeltoeOSS/Samples#22]
I have created a service registry and bound a service successfully. This may not be a issue, but I cannot consume application name to get the records. "http://csi-contactservice.cfapps.io/api/values" is working properly, but "http://csi-contactservice/api/values" doesn't work. Do I need to config DNS or what is the proper way of consuming a service-registry. 

![capture](https://user-images.githubusercontent.com/19770357/29759615-eaed33ae-8bda-11e7-9fbd-1f7b3886d202.PNG)

**Comment by dtillman** [comment]
Please see the Fortune Teller UI sample https://github.com/SteeltoeOSS/Samples/tree/master/Discovery/src/AspDotNetCore/Fortune-Teller-UI as well as the Discovery documentation http://steeltoe.io/docs/steeltoe-discovery/ .

Pay particular attention to the appsettings.json file and the https://github.com/SteeltoeOSS/Samples/blob/master/Discovery/src/AspDotNetCore/Fortune-Teller-UI/Services/FortuneService.cs 

If you are still having problems .. see me on the slack channel https://slack.steeltoe.io/
Dave
