### ISSUE TITLE
Custom queue object not receiving in Steeltoe rabbitMQ messaging

### ISSUE THREAD

**Issue by bradLucifer** [SteeltoeOSS/Samples#232]
## Describe the bug
I simply follow this article https://docs.steeltoe.io/guides/messaging/rabbitmq.html?tabs=cli but instead of passing data as `string`, i create a `custom object`   and pass it in queue. When i go to the `MonitorRabbitMQ project` and put a breakpoint on listener, it does not hit and i got some exceptions.

## Steps to reproduce 
1. follow this article https://docs.steeltoe.io/guides/messaging/rabbitmq.html?tabs=cli
2. Just create a Custom class say `CustomQueue` and pass it in queue e.g.
```
[Serializable]
    public class CustomQueue
    {
        public string Name { get; set; }
    }
```
3. Now in `MonitorRabbitMQ project`, change the param type e.g.
  ```
[RabbitListener(RECEIVE_AND_CONVERT_QUEUE)]
        public void ListenForAMessage(CustomQueue msg)
        {
            _logger.LogInformation($"Received the message '{msg}' from the queue.");
        }
```
4. In `MonitorRabbitMQ project`, i copy the `CustomQueue ` from WriteToRabbitMQ and put in `MonitorRabbitMQ project`
5. The problem is that it does not hit when we pass a custom object and when we pass string as param then it successfully hit 

## Expected behavior
It should receive custom object

## Environment (please complete the following information):
 - Messaging
 - Windows
 - NET Core 3.1
 - Steeltoe.Messaging.RabbitMQ Version=3.1.2

## Additional context or links
Got this exception
```
Steeltoe.Messaging.RabbitMQ.Listener.Exceptions.ListenerExecutionFailedException: Listener threw exception
 ---> Steeltoe.Messaging.Converter.MessageConversionException: failed to convert serialized Message content
 ---> System.Runtime.Serialization.SerializationException: Unable to find assembly 'WriteToRabbitMQ, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType(BinaryAssemblyInfo assemblyInfo, String name)
   at System.Runtime.Serialization.Formatters.Binary.ObjectMap..ctor(String objectName, String[] memberNames, BinaryTypeEnum[] binaryTypeEnumA, Object[] typeInformationA, Int32[] memberAssemIds, ObjectReader objectReader, Int32 objectId, BinaryAssemblyInfo assemblyInfo, SizedArray assemIdToAssemblyTable)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.ReadObjectWithMapTyped(BinaryObjectWithMapTyped record)
   at System.Runtime.Serialization.Formatters.Binary.BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(BinaryParser serParser, Boolean fCheck)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, Boolean check)
   at Steeltoe.Messaging.RabbitMQ.Support.Converter.SimpleMessageConverter.FromMessage(IMessage from, Type targetType, Object convertionsHint)
   --- End of inner exception stack trace ---
   at Steeltoe.Messaging.RabbitMQ.Support.Converter.SimpleMessageConverter.FromMessage(IMessage from, Type targetType, Object convertionsHint)
   at Steeltoe.Messaging.RabbitMQ.Listener.Adapters.MessagingMessageListenerAdapter.OnMessage(IMessage amqpMessage, IModel channel)
   at Steeltoe.Messaging.RabbitMQ.Listener.AbstractMessageListenerContainer.DoInvokeListener(IChannelAwareMessageListener listener, IModel channel, IMessage message)
   --- End of inner exception stack trace ---
```

**Comment by bradLucifer** [comment]
i think we have to serialize the object like this 
`_rabbitTemplate.ConvertAndSend(RECEIVE_AND_CONVERT_QUEUE, JsonConvert.SerializeObject(customMsg));`

and then make Listner like this

`[RabbitListener(RECEIVE_AND_CONVERT_QUEUE)]
        public void ListenForAMessage(string msg)
        {
            var x=JsonConvert.DeserializeObject<CustomQueue>(msg);
            _logger.LogInformation($"Received the message '{msg}' from the queue.");
        }`

**Comment by dtillman** [comment]
@bradLucifer : Yes, the problem you are seeing is that by default we use BinaryFormatter to serialize objects. As a result on the receiving side the deserialization attempts to deserialize the payload and expects to find the type available so that it can create an instance of it.  The type if finds is not the same one that is being sent because the assemblies they are in are different. So you have a couple options: 
1. Put the common type CustomQueue in a separate project and reference it the other  two rabbitmq projects.  That way the type will be common and in a shared assembly accessible by both.
2. Switch to using Json for the serialization protocol.
Dave

**Comment by bradLucifer** [comment]
thanks for your reply.
can you send me a sample project, it will really help me

Thanks in advance

**Comment by dtillman** [comment]
@bradLucifer : Which do you prefer  ..  1. Common project/.NET Serialization 2. JSON?

**Comment by bradLucifer** [comment]
If you have time then i want to look both

**Comment by dtillman** [comment]
@bradLucifer : https://github.com/SteeltoeOSS/Samples/tree/main/Messaging/src/RabbitMQWeb2

I think this should help... See the Startup.cs file in each project for how to enable/disable the .NET serialization vs JSON.

**Comment by bradLucifer** [comment]
Hi, binary serialization is obsolete and i want to use json serialization.
Can you explain it a little bit

**Comment by bradLucifer** [comment]
Thanks a lot.

**Comment by bradLucifer** [comment]
sorry to disturb you again.
But We have a flow
request -> MicroService1 (this service raise a event) -> Microservice2
(this service saves the data)
I have a scenario where i want to inform the UI that data is saved
successfully through microservice2 so what will be best approach that
should be adopted.

I have a approach:
1. Create a notification microservice and raise a event from Microservice2
which will be listened by Notification Service and it will have a signalR
set up in it and UI will be informed through it.

have you any other options, it will be really helpful if you suggest any
approach

Thanks in advance

**Comment by bradLucifer** [comment]
Hi,
getting a warning on Server in logs
Container AcknowledgeMode must be MANUAL for a Future<?> return type;
otherwise the container will ack the message immediately
