### ISSUE TITLE
When run Fortune-Teller-UI throw exception RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed

### ISSUE THREAD

**Issue by liu2510865** [SteeltoeOSS/Samples#25]
`Fortune-Teller-UI> fail: Steeltoe.CircuitBreaker.Hystrix.MetricsStream.HystrixMetricsStreamPublisher[0]
Fortune-Teller-UI>       Error creating connection/channel, metrics streaming disabled: RabbitMQ.Client.Exceptions.BrokerUnreachableException: None of the specified endpoints were reachable ---> RabbitMQ.Client.Exceptions.ConnectFailureException: Connection failed ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: 由于目标计算机积极拒绝，无法连接。 127.0.0.1:5672
Fortune-Teller-UI>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Fortune-Teller-UI>          at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
Fortune-Teller-UI>          at System.Net.Sockets.Socket.<>c.<ConnectAsync>b__267_0(IAsyncResult iar)
Fortune-Teller-UI>       --- End of stack trace from previous location where exception was thrown ---
Fortune-Teller-UI>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Fortune-Teller-UI>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Fortune-Teller-UI>          at RabbitMQ.Client.TcpClientAdapter.<ConnectAsync>d__2.MoveNext()
Fortune-Teller-UI>       --- End of stack trace from previous location where exception was thrown ---
Fortune-Teller-UI>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Fortune-Teller-UI>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Fortune-Teller-UI>          at RabbitMQ.Client.Impl.TaskExtensions.<TimeoutAfter>d__0.MoveNext()
Fortune-Teller-UI>       --- End of stack trace from previous location where exception was thrown ---
Fortune-Teller-UI>          at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Fortune-Teller-UI>          at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Fortune-Teller-UI>          at RabbitMQ.Client.Impl.SocketFrameHandler.Connect(ITcpClient socket, AmqpTcpEndpoint endpoint, Int32 timeout)
Fortune-Teller-UI>          --- End of inner exception stack trace ---
Fortune-Teller-UI>          at RabbitMQ.Client.EndpointResolverExtensions.SelectOne[T](IEndpointResolver resolver, Func`2 selector)
Fortune-Teller-UI>          at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
Fortune-Teller-UI>          --- End of inner exception stack trace ---
Fortune-Teller-UI>          at RabbitMQ.Client.ConnectionFactory.CreateConnection(IEndpointResolver endpointResolver, String clientProvidedName)
Fortune-Teller-UI>          at Steeltoe.CircuitBreaker.Hystrix.MetricsStream.HystrixMetricsStreamPublisher.SetupConnection()`

**Comment by dtillman** [comment]
Hi,
Were you trying to run the sample locally on your machine or on CloudFoundry?

I see 127.0.0.1:5672 in the log above, which makes me believe you were trying to run it locally or you were pushing to Cloud Foundry and you did not have a Hystrix dashboard bound to your application.

If  you were trying to run locally make sure you SET BUILD=LOCAL when running the application.

If you were pushing to CloudFoundry, then make sure you SET BUILD=, and then bind a Hystrix dashboard to your app.  Wait for the Hysrix dashboard service on Cloud Foundry to become available before pushing your app.

Dave
