### ISSUE TITLE
ETA for ASP.NET Core 2.0 support?

### ISSUE THREAD

**Issue by ReneHerrero** [SteeltoeOSS/Samples#26]
Hi,

Do you guys have an ETA for ASP.NET Core 2.0 support?

I've been able to get some of the Steeltoe components to work, but it seems 2.0 has introduced a few breaking changes...

Thanks,
René

**Comment by dtillman** [comment]
Hi,
Yes, you are correct on 2.0 ... we have begun working on 2.0.  If you explore the Dev NuGet feed for Steeltoe you will find packages that should work with ASP.NET Core 2.0 ... 

Keep in mind that this NuGet feed is our development feed and things might change over time.  

If you run into any problems using those bits we certainly would like to hear from you as they will eventually become our 2.0 final release. 

We have not yet determined when the final release date will be ...

https://myget.org/gallery/steeltoedev

Dave
