### ISSUE TITLE
AspDotNet4 Simple Config Sample does not work without modifications

### ISSUE THREAD

**Issue by jaredhwilliams** [SteeltoeOSS/Samples#27]
From the README at: https://github.com/SteeltoeOSS/Samples/blob/master/Configuration/src/AspDotNet4/Simple/README.md

Step 5 in the Pre-Requisites section (mvn spring-boot:run) does not work for me. When executing that step I was getting the following exception:
`[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:1.5.7.RELEASE:run (default-cli) on proj
ect spring-cloud-config-server: An exception occurred while running. null: InvocationTargetException: Error creating bea
n with name 'dataSource' defined in class path resource [org/springframework/boot/autoconfigure/jdbc/DataSourceConfigura
tion$Tomcat.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInst
antiationException: Failed to instantiate [org.apache.tomcat.jdbc.pool.DataSource]: Factory method 'dataSource' threw ex
ception; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationExce
ption: Cannot determine embedded database driver class for database type NONE. If you want an embedded database please p
ut a supported one on the classpath. If you have database settings to be loaded from a particular profile you may need t
o active it (no profiles are currently active). -> [Help 1]`

I was able to get it working by commenting out lines 25-29 from the pom.xml file at: https://github.com/spring-cloud/spring-cloud-config/tree/master/spring-cloud-config-server
`		`

Once I did this, the mvn spring-boot:run command completed successfully.

**Comment by dtillman** [comment]
Thanks,
We reported the issue to the Spring Config server team:
https://github.com/spring-cloud/spring-cloud-config/issues/819
