### ISSUE TITLE
When submit order,Error in event handler for(Unknown)

### ISSUE THREAD

**Issue by zzyykk123456** [SteeltoeOSS/Samples#28]
I followed this tutorial Using Steeltoe Docker images 
https://github.com/SteeltoeOSS/Samples/tree/master/MusicStore.  Login in,MusicList,AddCart all work ok.But when submit order,I get something like this:
![shoppayment0](https://user-images.githubusercontent.com/12078303/30948449-9a4d9d64-a442-11e7-833a-ad19e65465a0.png)
![shoppayment](https://user-images.githubusercontent.com/12078303/30948463-b905657a-a442-11e7-82d4-7a2f0b741204.png)

**Comment by TimHess** [comment]
Does the issue persist if you disable the Chrome Stylist plugin?

**Comment by zzyykk123456** [comment]
@TimHess  Thanks a lot.I have removed the Chrome Stylist plugin and the error above disappeared.It returns 200,but it does not redirect and  the table OrderDetails,Order both are empty.
![1](https://user-images.githubusercontent.com/12078303/31042139-b724416c-a5d3-11e7-82bc-66d6d5af9774.png)

**Comment by zzyykk123456** [comment]
@TimHess Thanks a lot.It does work.
