### ISSUE TITLE
Discovery:

### ISSUE THREAD

**Issue by bluedog13** [SteeltoeOSS/Samples#30]
How do I use "UseDiscoveryClient()" in a .net core console application?

A console application does not have IApplicationBuilder or middleware to call this method directly.

**Comment by dtillman** [comment]
@bluedog13 
Thanks for the input/question...

We worked on making this a bit easier in the 2.0 release and I've added a Console solution that has two .NET Core console apps, one that Registers a service .. and another that Fetches the services from the registry.

https://github.com/SteeltoeOSS/Samples/tree/dev/Discovery/src/Console

Hope that helps!
Dave

**Comment by TimHess** [comment]
@dlane771 this issue is closed, please file a new issue
