### ISSUE TITLE
Better describe the appconfig.json options

### ISSUE THREAD

**Issue by fabiousa7** [SteeltoeOSS/Samples#31]
Hi, 

The security samples shows that one could configure CloudFoundryAuthentication options within the appsettings.json, however all examples only show a small snippet of what it is supposed to look like. I tried adding a few other options but doesn't seem to work since the schema doesn't closely match CloudFoundryOptions class and i couldn't find the piece of code that applies those settings from the source code.

  ```
"security": {
    "oauth2": {
      "client": {
        "validate_certificates": false
      }
    }
  },
```

Could you please better document the full set of settings options available or point me to how you actually load these settings?

**Comment by dtillman** [comment]
@fabiousa7 
 
The code that binds the configuration to the Options is in the file referenced below.  It just uses the normal Microsoft Options binding mechanisms.  So you can simply look at the properties in the Options class (CloudFoundryOAuthOptions ) to see what settings are possible.

 (Note that when you push an app to CloudFoundry, AND you have bound to your app a OAuth service (e.g. UAA or Pivotal SSO) then the CloudFoundry service binding info will override what is provided in appsettings.json.

If you have more questions... open up another question or come over to our slack channel https://slack.steeltoe.io/

Dave

https://github.com/SteeltoeOSS/Security/blob/dev/src/Steeltoe.Security.Authentication.CloudFoundryCore/CloudFoundryExtensions.cs

Here is the snippet of the code that does the binding of configuration data to CloudFoundryOAuthOptions 

            builder.AddOAuth<CloudFoundryOAuthOptions, CloudFoundryOAuthHandler>(authenticationScheme, displayName, (options) =>
            {
                var securitySection = config.GetSection(CloudFoundryDefaults.SECURITY_CLIENT_SECTION_PREFIX);
                securitySection.Bind(options);

                SsoServiceInfo info = config.GetSingletonServiceInfo<SsoServiceInfo>();
                CloudFoundryOAuthConfigurer.Configure(info, options);
            });
