### ISSUE TITLE
Consolidate and update Management Samples

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Samples#325]
Rather than a collection of samples for actuators, let's use one or maybe two that can work in multiple scenarios (eg: Spring Boot Admin locally or in k8s, Apps Manager on TAS and ALV on TAP) that are rebuilt from .NET 8 templates

There is also a lot of cleanup needed with links to old Pivotal documentation

**Comment by bart-vmware** [comment]
@TimHess can this be closed? I suspect this was addressed in #343.

**Comment by TimHess** [comment]
Yes, this is done
