### ISSUE TITLE
Update image locations in CommonTasks and README files

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Samples#341]
As pointed out [here](https://github.com/SteeltoeOSS/Dockerfiles/pull/36#discussion_r1777639672), we're not publishing images to hub.docker.com anymore, and any documentation of our docker images needs to be updated accordingly

**Comment by bart-vmware** [comment]
Until this is implemented, https://github.com/SteeltoeOSS/Dockerfiles/pull/36#discussion_r1777533975 describes how to change existing commands.

> The docker commands change a little bit, but not by much (eg: steeltoe.azurecr.io/spring-boot-admin:3.3.3 compared with docker.io/steeltoeoss/spring-boot-admin:3.3.3, where docker.io/ was generally implicit).

**Comment by bart-vmware** [comment]
We may want to add `--pull-always` to the docker commands, to ensure a newer version is fetched when available.
