### ISSUE TITLE
Question : using HystrixCommand without inheriting from it ?

### ISSUE THREAD

**Issue by doubret** [SteeltoeOSS/Samples#35]
I'm new to hystrix and all examples i see use a service interface and implementation where the implementation inherits from the HystrixCommand class.

From what i see it's also possible to instantiate the command when needed and pass an anonymous method to it.
Is it considered a bad practice to use it this way ? Or is this just because most examples are implemented using the inheritance way ?

Thanks.

**Comment by dtillman** [comment]
Its just more common to derive from HystrixCommand and customize it as needed... 

There is no problem just doing new HystrixCommand()...

Dave

**Comment by doubret** [comment]
I saw a difference, request level caching is available only when inheriting as you have to override a virtual method.
