### ISSUE TITLE
Shell command samples in markdown should use the same code-fence language identifier

### ISSUE THREAD

**Issue by TimHess** [SteeltoeOSS/Samples#351]
For the sake of consistency, all of our generic shell command examples should use the same code-fence language identifier.

GitHub uses linguist, which appears to treat \```bash and \```shell [the same](https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml)

Unless we standardize on using the Microsoft [Learn Authoring Pack for Visual Studio Code](https://learn.microsoft.com/en-us/contribute/content/how-to-write-docs-auth-pack) (which doesn't like `shell`), we should make all references use `shell`

See also: https://learn.microsoft.com/en-us/contribute/content/code-in-docs#fenced-code-blocks

**Comment by bart-vmware** [comment]
I don't think using the authoring pack for samples makes sense. We're not publishing to a documentation website. So I propose to use ```shell``` everywhere in samples.

**Comment by TimHess** [comment]
I agree it's overkill and isn't _exactly_ the right tool for the job here, but I do like using it for catching things like MSFT docs links with language references like `/en-us/` in them, so I always have it on... Do you have anything else that catches things like that?

**Comment by bart-vmware** [comment]
No, I wasn't aware of that feature.
