### ISSUE TITLE
@GetAntiXsrfRequestToken()

### ISSUE THREAD

**Issue by pethumishara** [SteeltoeOSS/Samples#36]
how to access '@GetAntiXsrfRequestToken()' from external js file?

**Comment by TimHess** [comment]
@pethumishara to access .NET values from an external js file, you generally need to either use MVC to write the value to a JS variable from an MVC view (eg: `<script>var token='@GetAntiXsrfRequestToken()'</script>`)  or provide an endpoint to access the value (which is not likely to work in this scenario)
