### ISSUE TITLE
how to config appsettings  to use  username and password

### ISSUE THREAD

**Issue by akaxb** [SteeltoeOSS/Samples#40]
hi:
   i have a eureka service ,and It uses a security policy for username/password，my appsettings is like this
![001](https://user-images.githubusercontent.com/6300834/39190690-b03948ee-4807-11e8-8e88-22c9b0661d0a.png)
but it does not work, i can not register my service in it
so could you please  teach me how to config,thanks very much

**Comment by dtillman** [comment]
@akaxb,
Looks like we added support for the configuration values, but have not implemented the code to actually make use of it yet..

I'll add a story to our backlog to get the implementation done.

Dave
