### ISSUE TITLE
Add a Sample for Microsoft "eShopOnContainers" that utilize Steeltoe Features

### ISSUE THREAD

**Issue by yehia2amer** [SteeltoeOSS/Samples#41]
## **Need**
[**eShopOnContainers**](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/) [![GitHub stars](https://img.shields.io/github/stars/dotnet-architecture/eShopOnContainers.svg?style=flat-square&label=Star&maxAge=2592000)](https://github.com/dotnet-architecture/eShopOnContainers/star) [![GitHub forks](https://img.shields.io/github/forks/dotnet-architecture/eShopOnContainers.svg?user=dotnet-architecture&repo=eShopOnContainers&style=flat-square)](https://github.com/dotnet-architecture/eShopOnContainers/fork) is Great Sample Code reference for working with Microservices and Containers with .Net Core Created by Microsoft , that a lot of .Net developers consider as the Only mature reference for working with Microservices and containers in .Net Core.

I Think it will be a Great idea to Fork this Repo and Create based on it a Sample that Utilize all Steeltoe Great Features in one Project and even Replace the "musicStore" Sample with this eShopOnContainers.

## **Value**
Most of .Net developers now consider eShopOnContainers a Reference for Microservices, and it will be much easier for them to take a look at Steeltoe features and take a look and even compare them with the original project.

**Comment by TimHess** [comment]
This is a good idea, and it has been done before... we're working on getting an updated version of that conversion in here and will update the issue when it is available!

**Comment by yehia2amer** [comment]
Great to hear that, and waiting for this update.

**Comment by bingosummer** [comment]
@TimHess could you please share updates?

**Comment by TimHess** [comment]
There is a pull request to add this sample pending (https://github.com/SteeltoeOSS/Samples/pull/47) but the team hasn't had a chance to go through it yet. As I recall from conversation outside that PR, there's some additional work required to complete it.

**Comment by EdisonChou** [comment]
> There is a pull request to add this sample pending (#47) but the team hasn't had a chance to go through it yet. As I recall from conversation outside that PR, there's some additional work required to complete it.

Hope to see this in the near future, it will be a great sample for us to study!

**Comment by TimHess** [comment]
Rather than accept that PR, we made a fork, which you can find here: https://github.com/SteeltoeOSS/eShopOnContainers

As of today, our version has MySQL (with the Steeltoe EF Core connector), Steeltoe Management, Config Server and service discovery with Eureka
