### ISSUE TITLE
Error on pull docker image

### ISSUE THREAD

**Issue by guilhermeps** [SteeltoeOSS/Samples#42]
Guys, I really don't know if this is the right place to open this issue, but, when I was trying to pull the docker image, docker cli threws an exception telling that manifest for tag "latest" was not found. Can anyone help me? Thanks.

**Comment by ccheetham** [comment]
Please provide some additional information:
* docker image
* sample you're looking at
* client platform (Windows, OSX, etc)
* running docker command directly or via one of our scripts

**Comment by guilhermeps** [comment]
Ops, apologise me. 
I'm trying to run MusicStore on Windows 10. The docker image I'm talking about is the one provided on 
[https://hub.docker.com/r/steeltoeoss/servers/](url)

The command is bellow:
`docker pull steeltoeoss/servers`

**Comment by ccheetham** [comment]
The tag for this particular docker image is used to identify which server you're interested in using.

You can see the available tags here: https://hub.docker.com/r/steeltoeoss/servers/tags/

There are 2 such tags:
* eurekaserver1.0-linux
* configserver1.0-linux

As an example, to run the config server:
`> docker run -it --rm steeltoeoss/servers:configserver1.0-linux`

Perhaps worth highlighting that the `dockerrun-eurekaserver.cmd` and `dockerrun-configserver.cmd` scripts.  They will run the above docker containers for you and can provide some insight on how the `docker` command is invoked.
