### ISSUE TITLE
Cloud Configuration -Issue

### ISSUE THREAD

**Issue by shashi7403** [SteeltoeOSS/Samples#44]
Not able to get data from Repository. (Using Asp.Net.core) I have create the 
Service Config
Push to PCF.

Able to browse the page but not getting any value from Repository. Please help us  
Or
There have any way to do locally ?

**Comment by shashi7403** [comment]
Thanks for reply.Actually i am trying to connect Git hub respiratory via **CLOUD SERVER CONFIG**  
Created Config Server. but the Config Server cannot initialize using the configuration that has been provided.  Please advise
![image](https://user-images.githubusercontent.com/38246967/40200770-c49a81b4-5a3a-11e8-8479-fd512e4d8813.png)

**Comment by TimHess** [comment]
That message usually shows up when there's a network restriction preventing the config server from accessing GitHub.

In order for that configuration to work, your config server needs outbound internet access, at least to github.com

**Comment by shashi7403** [comment]
Thanks. but  from PCF  how will access ? as of now using company credential to login PCF. i am not sure how will get connect ?

Any other way to use fileSystem or any location where my Centralized config will available?

**Comment by shashi7403** [comment]
Thanks. Finally achieved the data from GitHub repository through steeltoe  and Cloud Server Config :)
Thanks a lot TIM for you help.

**Comment by TimHess** [comment]
You're welcome, I'm happy I could help!
