### ISSUE TITLE
Adding multiple eureka serviceurl instances 

### ISSUE THREAD

**Issue by devlkcsi** [SteeltoeOSS/Samples#45]
I am integrating Steeltoe Eureka in our project and for creating high availability servers I need to have multiple Serviceurl keys (eureka endpoints) in my configuration. Could you please help me to solve thing thing out.

**Comment by sunnycloudy** [comment]
from https://github.com/SteeltoeOSS/Discovery/issues/42
#-----
Our idea is:
Create a new adapter with multiple eureka service addresses when the source code is minimal changed. EurekaServerAdapter.Configuration multiple serviceurl like this: "http://eureka4.fat.com/eureka/,http://eureka1.fat.com/eureka/,http://eureka2.fat.com/eureka/".
#-----
There are three main point:
1. EurekaServerAdapter stores the eureka address set and the status of each address.
2.AddressExploration : probe address  by periodically polling each eureka server address and update the status
3  EurekaHttpClient#string _serviceUrl  will randomly takes the value of the EurekaServerAdapter#GetOnLineEurekaUrl  the address of the living eureka.
#------
f it is possible, can we make some pull request?

**Comment by TimHess** [comment]
We're open to accepting a pull request on this issue, but it should pretty closely follow how the Java client implements the feature, with particular attention to the way it works with zones/regions.

**Comment by dtillman** [comment]
@devlkcsi : @sunnycloudy We added multiple serviceUrls in 2.2 of Steeltoe

**Comment by dtillman** [comment]
@sunnycloudy @devlkcsi We added multiple URLs in 2.2 of Steeltoe
