### ISSUE TITLE
Not able to link groups in SAML response to Group Membership user attribute

### ISSUE THREAD

**Issue by MaheshRudrachar** [SteeltoeOSS/Samples#5]
Hi,

Using Pivotal SSO Service for authenticating and authorizing the users in .NET App. SSO Service is configured with external Ping Identity provider and SAML metadata is configured to make SSO service work. Authentication is working fine as expected using Authorization code from Steeltoe sample, but somehow group membership from SAML attributes are not getting properly mapped to scopes and hence policy claim is failing in .NET App.

Could someone help me in mapping ping identity groups to UAA scopes and additional configuration that needs to be configured in p-identity in order to authorize using [Authorize(Policy = "xyz")] in .NET App.

Regards
Mahesh

**Comment by dtillman** [comment]
@MaheshRudrachar : Mahesh, sorry for the late response ... are you still having this issue?  If so, I'll see if I can find someone that understands how Ping Identity/SAML/Pivotal SSO integration works... I have no hands on experience with Ping Identity...

Dave

**Comment by dtillman** [comment]
Closing due to no response.. Ping me if still issue
