### ISSUE TITLE
Update to ASP.Net Core 2.1 based.

### ISSUE THREAD

**Issue by mozts2005** [SteeltoeOSS/Samples#51]
Update the Project to be based on ASP.Net Core 2.1.X Templates

**Comment by TimHess** [comment]
As in re-evaluate all the samples? Is there something specific you noticed that needs to be addressed?

**Comment by mozts2005** [comment]
I had seen a number of issues in the Program.cs and Startup.cs looks as if they have been cleaned up.

The only issue can find now is https://github.com/SteeltoeOSS/Samples/blob/dev/Configuration/src/AspDotNetCore/SimpleCloudFoundry/Startup.cs#L45 

based on asp.net 2.1 this is a duplicate logging setup.
