### ISSUE TITLE
Not able to get data from config server when updated my app from 2.0 -> 2.1

### ISSUE THREAD

**Issue by chiragd03** [SteeltoeOSS/Samples#52]
Hello,
I have an existing web api project(dotnet core 2.0.7) which connects to Config Server and fetches data. I updated my project (dotnet core 2.1.0), and since then i am unable to fetch data from config server.
I only did the following changes to my project 

.csproj
Earlier
`<PropertyGroup>`
    `<TargetFramework>netcoreapp2.0</TargetFramework>`
  `</PropertyGroup>`
`<ItemGroup>`
    `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.7" />`
    `<PackageReference Include="Pivotal.Extensions.Configuration.ConfigServerCore" Version="2.0.0" />`
  `</ItemGroup>`

Now
`<PropertyGroup>`
    `<TargetFramework>netcoreapp2.1</TargetFramework>`
  `</PropertyGroup>`
`<ItemGroup>`
    `<PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0" />`
    `<PackageReference Include="Pivotal.Extensions.Configuration.ConfigServerCore" Version="2.1.0" />`
  `</ItemGroup>`

Can you please help

**Comment by TimHess** [comment]
Do you get any error messages? It could help if you [enable logging](https://steeltoe.io/docs/steeltoe-configuration/#2-2-6-enable-logging)

**Comment by chiragd03** [comment]
Hello @TimHess 
Thanks , i found the issue 
In the logs i found
`Could not locate PropertySource: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.`

This issue i was facing while using httpClient with dotnet core 2.1, as a fix i added
`AppContext.SetSwitch("System.Net.Http.UseSocketsHttpHandler", false);`
at the starting of Program.cs
Now its working fine.

Thanks again
