### ISSUE TITLE
Is there a plan similar to spring.cloud LCN at the back?

### ISSUE THREAD

**Issue by sundong1982** [SteeltoeOSS/Samples#54]
Distributed transaction

**Comment by TimHess** [comment]
Sorry, I'm not sure what you mean - can you provide a link or more information?

**Comment by sundong1982** [comment]
@TimHess I think Steeltoe OSS is a very good framework, but I find that it lacks distributed transaction support, such as sagas, tcc. If I do not support distributed transactions, it will be very difficult for me to use SteeltoeOSS in my future projects.

**Comment by jkonicki** [comment]
Closing in favor of #110
