### ISSUE TITLE
UAA sample is needed for local development

### ISSUE THREAD

**Issue by jkonicki** [SteeltoeOSS/Samples#55]
Currently, our UAA sample on works on CF.  It would be beneficial to have a sample for local development also.

**Comment by ccheetham** [comment]
The CI for CloudFoundrySingleSignon builds and published its own UAA app.

https://github.com/SteeltoeOSS/Samples/blob/2.x/Security/src/AspDotNetCore/CloudFoundrySingleSignon/CloudFoundrySingleSignon.feature#L13-L15

A local example could leverage this approach.
