### ISSUE TITLE
Unexpected character encountered while parsing value: . Path '', line 0, position 0.

### ISSUE THREAD

**Issue by khanhpv** [SteeltoeOSS/Samples#56]
Hi,
I have Eureka running on Ubuntu like this:
![image](https://user-images.githubusercontent.com/3120540/50205844-4a6dc480-039c-11e9-91bc-d8aee6a6886d.png)
But, every when I try to fetch Registry from Eureka, error occurs like this:
![image](https://user-images.githubusercontent.com/3120540/50205924-7e48ea00-039c-11e9-9693-447119fe71b2.png)
Attached to Visual Studio with pulled code from github, exception's thrown from:
![image](https://user-images.githubusercontent.com/3120540/50206028-bbad7780-039c-11e9-9946-e9ffd99bd5fb.png)
This is result from POSTMAN:
![image](https://user-images.githubusercontent.com/3120540/50206222-4d1ce980-039d-11e9-8dee-b22702fe838d.png)

Please have a look and let me know what's wrong with me.
Thanks a lot,

**Comment by TimHess** [comment]
Have you been able to resolve this? Can you share the response headers? I'm wondering if it could be something localization or character set related

**Comment by khanhpv** [comment]
It seemed the client had not added the Header "Accept: application/json", so, the result string could not be parsed to JSON format because it was XML format (default response of Eureka). I think so. Let me modify code to add the header into.

**Comment by khanhpv** [comment]
I have just seen the header existed already in code. So, it's not the problem I have told you.
Here is the response headers I've gotten:
![image](https://user-images.githubusercontent.com/3120540/50941530-e11f3400-14b7-11e9-8073-de67394bab63.png)

**Comment by khanhpv** [comment]
It is caused by gzip:
![image](https://user-images.githubusercontent.com/3120540/50942530-94d5f300-14bb-11e9-8337-86b1990d6fe9.png)
And, it seems the header was not sent to server:
![image](https://user-images.githubusercontent.com/3120540/50942569-b1722b00-14bb-11e9-8066-5ebd3b31c698.png)
Server response is still in xml format

**Comment by khanhpv** [comment]
This works, please update:
![image](https://user-images.githubusercontent.com/3120540/50943648-d8caf700-14bf-11e9-9e93-fece04aa80c9.png)

**Comment by dtillman** [comment]
@khanhpv, 
Yes, we will add support for GZip in 2.2... a PR would be welcome.. 

Dave

**Comment by dtillman** [comment]
@khanhpv : Gzip should be working in 2.2 of steeltoe
