### ISSUE TITLE
IPv6 should be absent but is instead null

### ISSUE THREAD

**Issue by frankdirosaiv** [SteeltoeOSS/Samples#58]
I've been testing out /Samples/Management/src/AspDotNetCore/Tracing/Fortune* project and Steeltoe has some pretty slick features. I was using the Zipkin Trace Exporter to send spans to a Zipkin server and everything worked as described (Awesome). However, I have a need to export these spans to a Jaeger server now (Written in Golang). Jaeger is supposed to be backwards compatible with Zipkin so this should not be a problem. But when I send traces to my Jaeger server I consistently receive a 400 Bad Request.

After digging a little deeper, it appears to happen when the Jaeger server is trying to parse the json body of trace information. Specifically, it looks like it is having trouble parsing "IPv6":null. According to the Zipkin [documentation](https://zipkin.io/zipkin-api/#/default/post_spans), IPv6 should be absent if unknown. So I tried sending an identical trace, but instead of IPv6 equaling null, IPv6 was absent. This **seems** to work.

Should IPv6 be present at all- if unkown? Does this sound like a Steeltoe problem? Is there a way to control the trace JSON that is sent when exporting traces?

**Comment by jkonicki** [comment]
Work to be done in https://github.com/SteeltoeOSS/management/issues/34
