### ISSUE TITLE
What is the best platform for the RabbitMQ customer, console application or web application?

### ISSUE THREAD

**Issue by ErikXu** [SteeltoeOSS/Samples#6]
The provided example use an MVC action to handle the RabbitMQ messages, it can only deal with one message when the action is invoked.
I think I need a service like window service to handle the messages in schedule, but there is not window service in .net core.
If I use the console application, maybe I can not use the services or middleware as there is no startup class, that means I can not use the steeltoe interfaces.
If I use the web application, I am not sure when or where to start listening.
Could you please provide some solutions or samples?

**Comment by dtillman** [comment]
@ErikXu:  If I get some time, I will try to create an example ... in the mean time, what I would probably do for a web application, would be to create a singleton service that encapsulates the rabbitmq connection and message handling.  When the service is created (i.e. by the container) you can start listening for messages.  The service could be created at App startup (i.e. in the Startup.cs class) via a GetService() call .. or lazily later during Controller creation, etc.. The constructor for the service would take as an argument the ConnectionFactory created by the Steeltoe connector.  Once the service is up and running you can start receiving messages and start processing.

Hope that helps... right now I just don't have time to create the sample... but I think it should be pretty simple.  Also: https://www.rabbitmq.com/dotnet-api-guide.html  .. is very useful of course...

**Comment by dtillman** [comment]
Closing due to no further discussion.. Ping me if you still need help
