### ISSUE TITLE
Problem with Discovery project

### ISSUE THREAD

**Issue by brezaie** [SteeltoeOSS/Samples#60]
Hi pals, I am going to run the discovery project. The service (fortuneService) gets registered in the Eureka, but when running the UI project, it cannot find the Random method in FortunesController ("http://fortuneService/api/fortunes/random"). 

I have also checked the "http://fortuneService/api/fortunes/random" in Postman and it does not find the endpoint either!

Could you please help me with the problem?

**Comment by TimHess** [comment]
Which sample are you using?

In our samples, the back-end service registers itself in a Eureka server with the name `fortuneService`, and the front-end (UI) apps use Eureka to resolve that service name to instance information (like host and port). Postman doesn't know how to ask Eureka how to find instances of that services.

**Comment by brezaie** [comment]
Dear TimHess,

I am running the .Net Core sample code presented in [https://github.com/SteeltoeOSS/Samples/tree/master/Discovery](here). First, I run the service project and it gets registered in the Eureka. When running the UI project, no response is returned from the service. I receive Bad Request from the following method:
`public async Task<string> RandomFortuneAsync()
        {
            try
            {
                var result = await _httpClient.GetStringAsync(RANDOM_FORTUNE_URL);
                _logger.LogInformation("RandomFortuneAsync: {0}", result);
                return result;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                throw;
            }
        }`

Could you please tell me the way I can solve the issue?

**Comment by TimHess** [comment]
I just tried running that sample, both in the dev(default) branch and master (the one you linked) -- the samples appear to be working as expected, it is likely there is something unexpected happening on your workstation. A bad request

You should be able to browse to the [eureka dashboard on your machine](http://localhost:8761/) to see how `fortuneService` registered itself. Clicking the link that is displayed with your service instance should result in a 404 as there is nothing listening at `/info` in that service, but if you change the path from `/info` to `/api/fortunes/random`, you should be able to see whether or not the service is in fact up and running at the location it has registered itself with eureka. On my machine, the service registered with `http://desktop-kml5ih5:5000` and I am able to get fortunes from `http://desktop-kml5ih5:5000/api/fortunes/random`.

I'd also recommend trying to run both apps from the command line. Sometimes the color coding in the console output is easier to read. You should see log entries for Steeltoe attempting to resolve the hostname. Here's a success:
```
dbug: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      LookupService(http://fortuneservice/api/fortunes/random)
dbug: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
      GetInstances returning: Instance[InstanceId=DESKTOP-KML5IH5:fortuneService:5000,HostName=DESKTOP-KML5IH5,IpAddr=10.0.75.1,Status=UP,IsUnsecurePortEnabled=True,Port=5000,IsSecurePortEnabled=False,SecurePort=443,VipAddress=fortuneService,SecureVipAddress=fortuneService,ActionType=ADDED]
dbug: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      Resolved fortuneservice to desktop-kml5ih5
dbug: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      LookupService() returning http://desktop-kml5ih5:5000/api/fortunes/random
```

and here's a failure
```
dbug: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      LookupService(http://fortuneservice/api/fortunes/random)
warn: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      Attempted to resolve service for fortuneservice but found 0 instances
dbug: Steeltoe.Common.Discovery.DiscoveryHttpClientHandler[0]
      LookupService() returning http://fortuneservice/api/fortunes/random
```

If that doesn't help you resolve, please provide the following:
- Your operating system
- .NET SDK version
- How you are running Eureka

**Comment by TimHess** [comment]
I'm assuming you were able to get this running, feel to re-open if you still need help
