### ISSUE TITLE
SSL problem trying to run eureka client against public docker image

### ISSUE THREAD

**Issue by autodidaddict** [SteeltoeOSS/Samples#8]
I get the following error when attempting to start up a simple Steeltoe client:

```
fail: Steeltoe.Discovery.Eureka.Transport.EurekaHttpClient[0]
      RegisterAsync Exception:
fail: Steeltoe.Discovery.Eureka.DiscoveryClient[0]
      Register failed, Exception: System.PlatformNotSupportedException: The libcurl library in use (7.51.0) and its SSL backend ("SecureTransport") do not support custom handling of certificates. A libcurl built with OpenSSL is required.
```

I am using .NET 1.0.1 tools and .NET 1.1 runtime.

**Comment by dtillman** [comment]
Hi Kevin,
I'm guessing you are running the sample on OSX .. here is the .NET Core github issue tracking this: https://github.com/dotnet/corefx/issues/9728 .   

As a work around, you can simply remove the validate_certificates config option in appsettings.json and the error should go away.  I've done that in the latest update that I just pushed .... I've moved the samples away from project.json and to .csproj.
